GAE-storage v0.7.1-SNAPSHOT (with Spine v0.7.5-SNAPSHOT)
SpineEventEngine/gcloud-java pull request #16
Opened 2017-01-10 16:23 UTC by dmdashenkov

2017-01-10 16:28 UTC, armiol requested changes
@dmdashenkov please see my comments.

2017-01-10 16:28 UTC, armiol commented on build.gradle
> +    STORAGE_VERSION = "0.7.1-SNAPSHOT"
Should be `GAE_JAVA_VERSION` instead, after the library name.

2017-01-10 16:28 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/Entities.java
> +     * <p>
Why do we need empty paragraphs? Here and below.

2017-01-10 16:41 UTC, dmdashenkov commented
@armiol Fixed your comments. PTAL again

2017-01-11 17:07 UTC, armiol approved these changes

2017-01-11 18:24 UTC, merged