Fix bulk read
SpineEventEngine/gcloud-java pull request #21
Opened 2017-02-01 13:54 UTC by dmdashenkov

- Provide the possibility to read more then __1000__ entities per one method call
 - Provide possibility to use and extend `DatastoreWrapper` from outside of the package
 - Remove consistency wait for the `dropTable` operation
 - Migrate to __Spine__ core __v0.8.0__
 - General clean up

2017-02-01 14:46 UTC, dmdashenkov commented
@armiol PTAL

2017-02-01 16:15 UTC, armiol requested changes
@dmdashenkov please see my comments.

2017-02-01 16:15 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DatastoreWrapper.java
> +     * <p>
Please remove extra `<p>` here and in similar cases.  We don't put those for an empty line.

2017-02-01 16:15 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DatastoreWrapper.java
> +    // Part of API
Please have a comment on the same line as a suppression. To be fixed in all cases like this.

2017-02-01 16:15 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DatastoreWrapper.java
> +    private List<Entity> readBigBulk(List<Key> keys) {
Let's have this method only and rename it to `readBulk`.
`smallBulk` is irrelevant, since it is impossible to guess, if the data is huge.

2017-02-01 16:15 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DatastoreWrapper.java
> +    private List<Entity> readBigBulk(List<Key> keys) {
It also requires JavaDocs, explaining the intention and some of GAE-specific details.

2017-02-01 16:15 UTC, armiol commented
@dmdashenkov also, I did not get this `Provide possibility to use and extend DatastoreWrapper from outside of the package`. I can see no evidence, since `DatastoreWrapper` is still `package-local`.

2017-02-01 16:28 UTC, dmdashenkov commented
Thanks for emphasizing the issue with `DatastoreWrapper`.

2017-02-01 17:36 UTC, dmdashenkov commented
@armiol PTAL

2017-02-02 11:07 UTC, armiol approved these changes
@dmdashenkov LGTM in general; please address my minor comments.

2017-02-02 11:07 UTC, armiol commented on gcd/src/test/java/org/spine3/server/storage/datastore/DatastoreWrapperShould.java
> +        // Wait some time to make sure the writing is complete
`Wait for some time ...`. And the dot at the end, since you started this comment as a sentence.

2017-02-02 11:07 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DatastoreWrapper.java
>   * <p>Provides API for Datastore to be used in storages.
Let's have a blank line above this `<p>`.

2017-02-02 11:35 UTC, merged