Datastore `Kind` improvements
SpineEventEngine/gcloud-java pull request #26
Opened 2017-03-29 09:27 UTC by dmdashenkov

Main changes:
 - Each `RecordStorage` has its own `kind` (determined by the record type name).
 - `DsPropertyStorage` uses `Descriptor` to store the values of single type under a single `kind`.

2017-03-29 09:28 UTC, dmdashenkov commented
@armiol, PTAL.

2017-03-29 09:28 UTC, dmdashenkov commented
@armiol, let's discuss the version number for this incrementation.

2017-03-29 13:27 UTC, armiol requested changes
@dmdashenkov Take a look at the comments. Also, let's make the `getKind()` a `protected` method with a default implementation.

2017-03-29 13:27 UTC, armiol commented on gcd/src/test/java/org/spine3/server/storage/datastore/DatastoreStorageFactoryShould.java
> +    private static class  DifferentTestEntity extends AbstractEntity<String, Project> {
Please adjust the formatting.

2017-03-29 13:27 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsRecordStorage.java
> +    String getKind() {
Let's make a simple value object for `Kind`. It should be immutable and `final`, with a factory method, which validates for `null` etc.

2017-03-29 13:29 UTC, armiol commented
@dmdashenkov let's just increase the second minor.

2017-03-29 15:53 UTC, dmdashenkov commented
@armiol, PTAL again.

2017-03-30 12:40 UTC, armiol requested changes
@dmdashenkov take a look at my comments.

2017-03-30 12:40 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsStandStorageDelegate.java
> + * @author Dmytro Dashenkov
Let's describe it first before I could look at it.

For now it is completely unclear.

2017-03-30 12:40 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/Kind.java
> + * @author Dmytro Dashenkov
Same as above. 

I would also consider hiding these classes from `public`. Please review and determine which of those are really `public`.

2017-03-30 12:40 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsProperties.java
> +    static Predicate<Entity> activedEntityPredicate() {
Something is wrong with English in this name.

And also, why is it in the `DsProperties`? Does not seem to be a good place for such a common thing.

2017-03-30 13:24 UTC, dmdashenkov commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsProperties.java
> +    static Predicate<Entity> activedEntityPredicate() {
The point is that this predicate matches the Datastore `Entity`, not any of our types.
As for me, this should stay in `DsProperties` as it's relevant to the Datastore properties.

BTW, let's discuss if we should remove this at all and migrate to using `Query` instead.

2017-03-30 13:25 UTC, dmdashenkov commented
@armiol, PTAL again.

2017-03-31 13:57 UTC, armiol requested changes
@dmdashenkov please create `KindShould` as then LGTM.

2017-03-31 13:59 UTC, armiol commented
@dmdashenkov one more thing. Could you please append the PR description with the details on how the underlying storage is going to be organized for those, who use `RecordStorage`. A few sentences with an example (say, a couple of `ProjectionRepository` classes) is enough.

2017-03-31 14:59 UTC, dmdashenkov commented
@armiol, PTAL again at the changes and the PR description.
Is that what you expected?

2017-03-31 15:56 UTC, armiol approved these changes
@dmdashenkov LGTM.

2017-04-03 09:16 UTC, merged