`Stringifiers` for all the IDs when converting to String
SpineEventEngine/gcloud-java pull request #29
Opened 2017-04-05 12:48 UTC by dmdashenkov

Before we had `Stringifiers`, `Identifiers` and `IdTransformer` for converting the IDs to `String` and vise versa. Now it's only the duty of `Stringifiers`.
After migrating to core v0.8.30 ([#419](https://github.com/SpineEventEngine/core-java/pull/419)) the `IdTransformer` class should be removed at all.

2017-04-05 12:54 UTC, dmdashenkov commented
@armiol, PTAL.

2017-04-05 15:12 UTC, armiol requested changes
@dmdashenkov see my comment.

2017-04-05 15:12 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsRecordStorage.java
> +        final LifecycleFlags flags = getLisececleFlags(response);
Please, do not create any commits in a hurry.

2017-04-11 15:32 UTC, dmdashenkov commented
@armiol, PTAL.

I suppose this to be merged into `master` after the `entity-storage-fields` branch is merged.

2017-04-12 09:12 UTC, closed without merging