Entity Column queries
SpineEventEngine/gcloud-java pull request #42
Opened 2017-05-05 14:02 UTC by dmdashenkov

Support for the `EntityQuery`.

## WIP

__Note:__ increment version of `gae-java` to `0.9.0` before merging this.

2017-05-12 12:29 UTC, dmdashenkov commented
@armiol, PTAL.

2017-05-12 13:00 UTC, armiol requested changes
@dmdashenkov LGTM in general. But the coverage does not seem to be thorough. See my comments on this matter; also please re-check yourself. 

The querying feature is very important, so the new code should be covered.

2017-05-12 13:00 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsRecordStorage.java
> +    @SuppressWarnings("unchecked") // Precise column type is undefined
`Exact column type is unknown at this stage.`

2017-05-12 13:00 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsRecordStorage.java
> +    private Filter buildColumnPredicate(Map<Column<?>, Object> columns) {
Please call the methods, which return `Filter`, accordingly. Right now they are called like they return `Predicate`.

2017-05-12 13:00 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/type/DsColumnTypes.java
> +            return StringValue.of(data);
This line is reported to be untested.

2017-05-12 13:00 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/type/DsColumnTypes.java
> +            return LongValue.of(data);
This line is reported to be untested.

2017-05-12 13:00 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/type/DsColumnTypes.java
> +            return BooleanValue.of(data);
Same as above.

2017-05-12 13:00 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/type/DsColumnTypes.java
> +            return DateTimeValue.of(data);
Same as above.

2017-05-12 13:00 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/type/DsColumnTypes.java
> +            return StringValue.of(data);
Same as above.

2017-05-12 13:00 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/type/AbstractDatastoreColumnType.java
> +        final Value<?> dsValue = toValue(value);
The body of this method is reported to be untested.

2017-05-12 16:10 UTC, dmdashenkov commented
@armiol, PTAL.

2017-05-13 12:32 UTC, armiol approved these changes
@dmdashenkov LGTM.

2017-05-14 09:23 UTC, merged