Advanced Entity Queries
SpineEventEngine/gcloud-java pull request #47
Opened 2017-05-31 16:14 UTC by dmdashenkov

This PR brings the support of the advanced Entity Queries to __gae-java__.

## WIP

2017-06-01 17:20 UTC, dmdashenkov commented
@armiol, PTAL.

2017-06-01 17:58 UTC, armiol requested changes
@dmdashenkov LGTM except for some minor comments.

Also, please review the version number before actual merge.

Any comments that you may have let's discuss vocally.

2017-06-01 17:58 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/ColumnHandler.java
> + * A wrapper above the {@link ColumnTypeRegistry} preforming the transformations defined by
`preforming` is a typo.

And it's a transformer, not a wrapper (which BTW is just some implementation details, that we can omit at all).

2017-06-01 17:58 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/ColumnHandler.java
> +    static ColumnHandler wrap(ColumnTypeRegistry<? extends DatastoreColumnType> registry) {
I'd call it `of`.

2017-06-01 17:58 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/ColumnHandler.java
> +        @SuppressWarnings("unchecked") // Concrete type is unknown on compile time.
I would say it's possible to introduce a generic parameter just for this method. It's still going to be "unchecked", but at least we'll know that the cast is performed to the exact type requested.

Let's discuss.

2017-06-01 17:58 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsFilters.java
> +                    return input != null && input.getOperator() == ALL;
To me, the `input` being `null` is an `IllegalArgumentException`.

2017-06-01 17:58 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsFilters.java
> +     * {@link Filter}s.
`{@linkplain Filter Filters}`.

2017-06-01 17:58 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsFilters.java
> +     * <p>Given query predicates {@code p1}, {@code p2}, {@code p3}, {@code p4}, {@code p5} passed
Please allow an empty line before this `<p>`.

Also this example paragraph should be formatted better. It's a bit difficult to read ATM.

2017-06-01 17:58 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/ColumnHandler.java
> +final class ColumnHandler {
We need a new name for this class. This isn't a handler by any means.

2017-06-02 10:44 UTC, dmdashenkov commented
@armiol, PTAL again.

2017-06-02 14:50 UTC, armiol requested changes
@dmdashenkov LGTM except for naming.

2017-06-02 14:50 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/ColumnTypeConverter.java
> +final class ColumnTypeConverter {
`ColumnValueAdapter`. Let's update the Javadocs accordingly.

2017-06-02 14:50 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsFilters.java
> +    private interface ConjunctionProcessor {
In fact this is a `Function<Queue<ColumnFilterNode>, Void>`.

2017-06-02 14:50 UTC, armiol commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsFilters.java
> +    private static class ColumnFilterShrinker implements ConjunctionProcessor {
I think it's `ColumnFilterReducer`, judging on the documentation.

2017-06-06 14:35 UTC, dmdashenkov commented on gcd/src/main/java/org/spine3/server/storage/datastore/DsFilters.java
> +    private interface ConjunctionProcessor {
This doesn't look a proper usage of `Function` to me.
Moreover, the custom type provides a description of the usage of the type instances and `Function<Node, Void>` says nothing about both the function itself and the parameter.

2017-06-06 15:52 UTC, dmdashenkov commented
@armiol, PTAL.

2017-06-06 16:05 UTC, armiol requested changes
@dmdashenkov please see my comments, let's discuss.

2017-06-06 16:05 UTC, armiol commented on gcd/src/main/java/io/spine/server/storage/datastore/DsFilters.java
> +     * the {@linkplain #fromParams parenthesis opening algorithm}.
Let's rephrase this. `parenthesis opening` isn't what it is called. It's called `multiply brackets`, `expand brackets`, `simplify brackets` etc.

2017-06-06 16:05 UTC, armiol commented on gcd/src/main/java/io/spine/server/storage/datastore/DsFilters.java
> +         * Processes the found conjunction.
This isn't good enough either. The description doesn't really explain why there is a `Queue<...>`, not just the "found conjunction".

2017-06-06 16:42 UTC, dmdashenkov commented
@armiol, PTAL at the docs change.

2017-06-07 10:44 UTC, dmdashenkov commented
@armiol, PTAL.

2017-06-07 11:02 UTC, armiol approved these changes
@dmdashenkov LGTM.

2017-06-07 13:55 UTC, dmdashenkov commented
@armiol, PTAL.

2017-06-07 14:06 UTC, armiol commented on README.md
> +To use `gae-java`, you should configure the Datastore indexes for the Spine internal record types.
```
#### Datastore indexes

In order to run the application built on top of `gae-java`, Datastore instance requires some preliminary configuration. In particular, the indexes for the Spine internal record types should be set. 

The configuration file is located at `./gcd/config/index.yaml`. 

Please see the [Google Cloud Platform documentation](https://cloud.google.com/datastore/docs/tools/indexconfig) for the details.

##### Custom indexes

It is possible to store some of the Spine `Entity` fields in separate Datastore kind fields. Such an approach is useful to optimize read-side querying. In this case more Datastore indexes may be created.

__Example:__

...
```

2017-06-08 12:02 UTC, merged