Dependencies catch up
SpineEventEngine/gcloud-java pull request #49
Opened 2017-06-30 14:44 UTC by dmdashenkov

In this PR we:
 - update Spine dependencies to the state of the art;
 - update Datastore API dependency to `v1.2.1` (the freshest);
 - perform misc clean-up in the build scripts.

## WIP

2017-07-03 14:12 UTC, dmdashenkov commented
@armiol, PTAL.

The build still fails since the core version is not in the artifactory yet.

2017-07-03 14:15 UTC, armiol requested changes
@dmdashenkov please see my comments.

2017-07-03 14:15 UTC, armiol commented on build.gradle
> +
Please remove this line.

2017-07-03 14:15 UTC, armiol commented on ext.gradle
> +    VERSION = SPINE_VERSION
Please have the same camel-case format as in `core-java`.

2017-07-03 14:15 UTC, armiol commented on ext.gradle
> +    IS_WINDOWS = org.gradle.internal.os.OperatingSystem.current().isWindows()
The idea of `ext.gradle` is to externalize the reusable dependency list, which is being changed on a regular basis. This variable does not belong to `ext.gradle`.

2017-07-03 14:15 UTC, armiol commented on build.gradle
> +void dependOnSpine(final dependencyHandler,
Let's not have that at all. It's way more lines than having just a list of dependencies explicitly.

Also, if you want to exclude some of transitive dependencies, you could have a collection in the same way and pass it to `excludes: ` section in each case. Or use global `configurations.all { ...}`.

2017-07-03 14:15 UTC, armiol commented on build.gradle
> +                         'spine-core': VERSION,
I think the `spine-core` and `spine-base` dependencies should not be here, as you'll get those anyway.

2017-07-03 14:15 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DatastoreStorageFactory.java
> +        final DsRecordStorage<I> recordStorage = (DsRecordStorage<I>) createRecordStorage((Class<? extends Entity<I, ?>>) projectionClass);
Please fit 100 symbols wide.

2017-07-03 14:15 UTC, armiol commented on datastore/src/test/java/io/spine/server/storage/datastore/DsRecordStorageShould.java
> +    // ----- Test Entity Types ------
Please the section title according to our guidelines. See the `core-java` wiki.

2017-07-03 14:15 UTC, armiol commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-bin.zip
I think JAR file should be updated as well. Maybe, the `.bat`/`.sh` scripts also.

2017-07-03 15:30 UTC, dmdashenkov commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-bin.zip
Done.

2017-07-04 11:49 UTC, dmdashenkov commented
@armiol, PTAL.

2017-07-10 11:44 UTC, dmdashenkov commented
@armiol, PTAL.

2017-07-10 13:36 UTC, armiol approved these changes
@dmdashenkov LGTM except for a few things. Please address those and feel free to merge.

2017-07-10 13:36 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DatastoreStorageFactory.java
> +                "Datastore namespace should not be configured explicitly for a multitenant " +
```
"Datastore namespace should not be configured explicitly" +
"for a multitenant storage"
```

2017-07-10 13:36 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DatastoreStorageFactory.java
> +                "Setting a custom NamespaceToTenantIdConverter to a single-tenant storage factory" +
```
"Setting a custom NamespaceToTenantIdConverter is not allowed" + 
" for a single-tenant storage factory."
```

2017-07-10 13:36 UTC, armiol commented on datastore/src/test/java/io/spine/server/datastore/TestEnvironment.java
> + * A utility class for investigating the test environment at runtime.
`for analyzing`/`for detecting`

2017-07-10 13:36 UTC, armiol commented on datastore/src/test/java/io/spine/server/storage/datastore/given/Given.java
> +    public static final String TEST_PROJECT_ID_VALUE = "spine-dev";
Please expose those as static methods instead.

2017-07-11 12:26 UTC, armiol commented
@dmdashenkov LGTM. I approved this PR yesterday :)

2017-07-12 12:53 UTC, merged