Optimize reading of aggregates
SpineEventEngine/gcloud-java pull request #61
Opened 2017-10-11 12:58 UTC by dmytro-grankin

This PR fixes #60.

Recently, `Storage.read(...)` method was reworked. See details in the [PR](https://github.com/SpineEventEngine/core-java/pull/596).

`DsAggregateStorage` was updated. And now it uses a batch size from the newly introduced `AggregateReadRequest` as a limit for `StructuredQuery`. Explanations of limits for Datastore can be found [here](https://cloud.google.com/datastore/docs/concepts/queries#cursors_limits_and_offsets).

The Spine version was increased to `0.9.75-SNAPSHOT`.

2017-10-11 13:49 UTC, dmytro-grankin commented
@armiol PTAL.

2017-10-11 14:08 UTC, armiol reviewed
@dmytro-grankin please see my comments. 

Also, as discussed, let's create a test, that verifies reading of an `Aggregate` instance in case snapshot trigger is changed to a smaller value in the middle of operation.

2017-10-11 14:08 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DsAggregateStorage.java
> +     * by batches. Size of a batch is specified by the given {@link AggregateReadRequest}.
```
...will fetch {... events} batch by batch.

<p>The size of the batch is specified ...
```

2017-10-11 14:08 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DsAggregateStorage.java
> +                    .setOrderBy(byCreatedTime(),
One more issue should be addressed within this method. 

At the moment we order by created time and only then by version. In fact, ordering by version is more important and must come first. Please address that and include to the PR description.

2017-10-12 11:09 UTC, dmytro-grankin commented on datastore/src/main/java/io/spine/server/storage/datastore/DsAggregateStorage.java
> +     * by batches. Size of a batch is specified by the given {@link AggregateReadRequest}.
Done.

2017-10-12 11:09 UTC, dmytro-grankin commented on datastore/src/main/java/io/spine/server/storage/datastore/DsAggregateStorage.java
> +                    .setOrderBy(byCreatedTime(),
Done.

2017-10-12 11:16 UTC, dmytro-grankin commented
@armiol PTAL.

2017-10-12 11:28 UTC, armiol requested changes
@dmytro-grankin Mostly LGTM. However, a few things still to address.

2017-10-12 11:28 UTC, armiol commented on datastore/src/test/java/io/spine/server/storage/datastore/DsAggregateStorageShould.java
> +    public void allow_aggregate_loading_if_snapshot_trigger_was_decreased_in_AggregateRepository() {
To emphasize those parts that matter, I would name it 
`still_load_aggregates_properly_after_snapshot_trigger_decrease_at_runtime`.

2017-10-12 11:28 UTC, armiol commented on datastore/src/test/java/io/spine/server/storage/datastore/DsAggregateStorageShould.java
> +    private static void register(AggregateRepository repository) {
Let's move things like this one to `Given` (similar to what we do in `core-java`). This method is both excessive in the test code and weird — as it's `static`, looks like a registration, but in fact creates a bounded context each time.

Let's discuss if needed. But at the moment this piece of code is difficult to reuse properly.

2017-10-12 11:43 UTC, dmytro-grankin commented
@armiol PTAL.

2017-10-12 11:58 UTC, armiol approved these changes
@dmytro-grankin LGTM with a couple of issues to address.

2017-10-12 11:58 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DsStandStorage.java
>      @Nullable
I think it's not `@Nullable`. As long as you modify this method, please pay attention to things like that.

2017-10-12 11:58 UTC, armiol commented on datastore/src/test/java/io/spine/server/storage/datastore/DsAggregateStorageShould.java
> +    private static class ProjectAggregateRepository
Please move this class to `Given` (like we do in `core-java`) and have a class-level comment for it.

2017-10-12 12:19 UTC, merged