WIP: Implement limit and order
SpineEventEngine/gcloud-java pull request #94
Opened 2018-10-18 20:05 UTC by mdrachuk

2018-10-19 11:10 UTC, mdrachuk commented on datastore/src/main/java/io/spine/server/storage/datastore/DsEntityComparator.java
> +            return type == valueType;
Does not apply: ValueType is an enum.

2018-11-02 01:25 UTC, mdrachuk commented
@armiol, PTAL. I still need to fix code coverage, but this won’t change the existing code.

2018-11-02 10:16 UTC, armiol requested changes
@mdrachuk please see my comments.

2018-11-02 10:16 UTC, armiol commented on .travis.yml
> +  - secure: N30+tQHzr7i05iIbVf6YAk7i3ykPjZLxEZur3cZWh5vwD4TmQI9FDZ5vVJo3HWulb8tCV5jFM0RXwo2nswhq2G8WGJY6DkjICF1/U3FPax2VdgDEMScfULvRbt5f6NugHo5sbUuVPukVKv4+7LBdOuBOFXQ92OfEm9HQVO6PSzg5jgHeSJSEmh1cW+Z
Please comment on purpose.

2018-11-02 10:16 UTC, armiol commented on build.gradle
> +    apply plugin: 'idea'
I don't think we need that for the root project. So consider moving this to `subprojects`.

2018-11-02 10:16 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DatastoreWrapper.java
> +     * <p>The results are returned in an order matching that of the provided keys with nulls
`{@code null}s`

2018-11-02 10:16 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DatastoreWrapper.java
> +        return stream(keys)
Please extract the returning value into a variable.

2018-11-02 10:16 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DatastoreWrapper.java
> +    private Iterator<Entity> readAllInBatches(StructuredQuery<Entity> query,
Let's name it `readAll`. The `batchSize` parameter tells us about the batches.

2018-11-02 10:16 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DsEntityComparator.java
> +        //noinspection unchecked entity values are required to be comparable by Spine
Please fix this `noinspection`.

2018-11-02 10:16 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DsLookupByIds.java
> +        return read(ids)
Please extract a variable before returning the value.

2018-11-02 10:16 UTC, armiol commented on datastore/src/main/java/io/spine/server/storage/datastore/DsLookupByIds.java
> +        return read(ids)
Same as above.

I also don't understand why this method and the method above do not share any code. Please review this method and all the similar methods below for returning the variable (useful for inspecting in debug) and for the code duplication.

2018-11-03 16:33 UTC, armiol approved these changes

2018-11-03 17:06 UTC, merged